"""Run the scene board's paging receipts and summarise them (ruling 255).

Runs `paging_receipts_at_256` and `paging_receipts_headroom` from
`crates/isometry-views` in the debug and release builds, keeps each raw log
out of tree, and writes the summary and the raw-receipt manifest beside this
script:

    python testing/scene-board-paging/receipts.py [--out DIR] [--builds debug,release]
        [--host NAME=EXE ...] [--check NAME=EXE=LAYERS ...]
    python testing/scene-board-paging/receipts.py --summarise-only [--out DIR]

Each `--host` runs the two headed sessions `headed.py` describes with one
shipping host binary, into `DIR/host-<n>-<NAME>`, in the order given; it needs
a desktop session. Each `--check` runs the 256 session once more at that
headroom, into `DIR/headroom-check/headroom-<LAYERS>-run-<n>`, after the hosts.

DIR defaults to ~/Code/testing/isometry/receipts/2026-09-26/scene-board-paging/
<commit>, the machine's out-of-tree receipt directory with one folder per
round, so a round never overwrites the files an earlier manifest hashed.
`--summarise-only` rebuilds the summary from logs already there, so a copy
checked against RAW_RECEIPTS.md can be summarised again without re-running
anything. Each log opens with the commit, command and compiler that produced
it.
"""

import argparse
import hashlib
import json
import pathlib
import statistics
import subprocess
import sys
from collections import defaultdict

import headed

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parents[1]
RECEIPTS = (
    pathlib.Path.home() / "Code" / "testing" / "isometry" / "receipts" / "2026-09-26"
    / "scene-board-paging"
)
TAG = "[paging-receipt] "
NEWLINE = chr(10)


def output(command: list[str]) -> str:
    return subprocess.run(
        command, cwd=ROOT, capture_output=True, text=True, check=True
    ).stdout.strip()


def run(build: str, out: pathlib.Path) -> pathlib.Path:
    command = ["cargo", "test", "-p", "isometry-views", "--lib"]
    if build == "release":
        command.append("--release")
    command += ["paging_receipts", "--", "--ignored", "--nocapture", "--test-threads=1"]
    header = NEWLINE.join([
        f"# commit {output(['git', 'rev-parse', 'HEAD'])}",
        f"# build {build}: {' '.join(command)}",
        f"# {output(['rustc', '-V'])}",
        "",
    ])
    log = out / f"{build}.log"
    result = subprocess.run(command, cwd=ROOT, capture_output=True)
    divider = (NEWLINE + "--- stderr ---" + NEWLINE).encode()
    log.write_bytes(header.encode() + result.stdout + divider + result.stderr)
    if result.returncode != 0:
        sys.exit(f"{' '.join(command)} failed; see {log}")
    return log


def provenance(log: pathlib.Path) -> str:
    """The commit a log's header names."""
    first = log.read_text(encoding="utf-8", errors="replace").splitlines()[0]
    return first.removeprefix("# commit ").strip()


def records(log: pathlib.Path) -> list[dict]:
    # The first receipt shares its line with libtest's `test <name> ...`.
    rows = []
    for line in log.read_text(encoding="utf-8", errors="replace").splitlines():
        at = line.find(TAG)
        if at >= 0:
            rows.append(json.loads(line[at + len(TAG):]))
    return rows


def median(values):
    values = [v for v in values if v is not None]
    return statistics.median(values) if values else None


def ms(value) -> str:
    return "-" if value is None else f"{value:,.2f}"


def summarise(rows: list[dict]) -> str:
    base = {(r["build"], r["board"]): r for r in rows if r["kind"] == "baseline"}
    spare = [r for r in rows if r["kind"] == "headroom" and r["build"] == "release"]
    groups = defaultdict(list)
    for r in rows:
        if r["kind"] not in ("baseline", "headroom"):
            groups[(r["build"], r["board"], r["pane"], r["kind"])].append(r)
    keys = sorted({k[:3] for k in groups})
    work = lambda r: r["columns_ms"] + r["diff_ms"] + r["fill_ms"]  # noqa: E731
    out = [
        "# Scene board paging receipts, 2026-09-26",
        "",
        "Generated by `receipts.py` from the raw logs named in `RAW_RECEIPTS.md`.",
        "Medians over each run's samples. Every timing is one build on one",
        "machine and moves with both; every count and byte figure does not.",
        "",
        "## One click at 256 by 256",
        "",
        "A click selects a tile, which tints its top voxel. Before paging it",
        "raised the whole ground and compared it brick by brick; now it reads",
        "one column per tile, diffs them and remakes the held bricks it touched.",
        "",
        "| build | board | pane | before: regrow + diff, ms | now: columns + diff + fill, ms"
        " | frame, ms | slots | upload, bytes |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for build, board, pane in keys:
        clicks = groups.get((build, board, pane, "select"), [])
        if not clicks:
            continue
        old = base.get((build, board))
        before = old["grow_ms"] + old["diff_ms"] if old else None
        out.append(
            f"| {build} | {board} | {pane} | {ms(before)} | {ms(median(map(work, clicks)))} "
            f"| {ms(median(r['draw_ms'] for r in clicks))} "
            f"| {median(r['slots'] for r in clicks)} "
            f"| {median(r['upload_bytes'] for r in clicks):,.0f} |"
        )
    out += [
        "",
        "## One raise, one pan",
        "",
        "A raise lifts one tile a step. A pan moves the camera a tile across or",
        "half a tile down: it reads nothing and retargets, a shrinking framing",
        "included, and rebuilds only when the camera outgrows the pointer volume.",
        "",
        "| build | board | pane | kind | n | columns + diff + fill, ms | frame, ms"
        " | loaded | retargets | rebuilds | upload, bytes |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for build, board, pane in keys:
        for kind in ("raise", "pan"):
            sample = groups.get((build, board, pane, kind), [])
            if not sample:
                continue
            retargets = sum(
                1 for r in sample if r["rebuilt"] is None and r["loaded"] + r["evicted"] > 0
            )
            rebuilds = sum(1 for r in sample if r["rebuilt"] is not None)
            out.append(
                f"| {build} | {board} | {pane} | {kind} | {len(sample)} "
                f"| {ms(median(map(work, sample)))} "
                f"| {ms(median(r['draw_ms'] for r in sample))} "
                f"| {median(r['loaded'] for r in sample)} | {retargets} | {rebuilds} "
                f"| {median(r['upload_bytes'] for r in sample):,.0f} |"
            )
    out += [
        "",
        "## What the frame holds",
        "",
        "| build | board | pane | bricks on the board | resident | capacity | past the atlas"
        " | first frame, ms | first fill, ms |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for build, board, pane in keys:
        first = groups.get((build, board, pane, "first"), [])
        held = [r for k, v in groups.items() if k[:3] == (build, board, pane) for r in v]
        if not first:
            continue
        old = base.get((build, board))
        out.append(
            f"| {build} | {board} | {pane} | {old['bricks'] if old else '-'} "
            f"| {min(r['resident'] for r in held)} to {max(r['resident'] for r in held)} "
            f"| {first[0]['capacity']} | {max(r['overflow'] for r in held)} "
            f"| {ms(first[0]['draw_ms'])} | {ms(first[0]['fill_ms'])} |"
        )
    return NEWLINE.join(out + headroom(spare)) + NEWLINE


def headroom(rows: list[dict]) -> list[str]:
    """What each spare layer costs the pointer volume. The counts are the
    build's and not the machine's, so one build's rows stand for both."""
    if not rows:
        return []
    out = [
        "",
        "## What each spare layer of headroom costs",
        "",
        "The pointer volume reserves brick layers above the board's tallest tile,",
        "so an edit that lifts it into them retargets rather than rebuilding the",
        "map. The default, one spare layer, is provisional: Mark takes it back with",
        "these numbers. A spare layer widens the volume a little as well as raising",
        "it, because the camera leans. The pointer volume is uploaded whole with",
        "every retarget, so its bytes are also what each pan uploads before its",
        "bricks. The atlas does not move with the headroom.",
        "",
        "| board | pane | headroom | reserved layers | pointer extent | pointer, bytes"
        " | per layer, bytes | atlas, bytes |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    previous = {}
    for r in sorted(rows, key=lambda r: (r["board"], r["pane"], r["headroom"])):
        key = (r["board"], r["pane"])
        step = r["pointer_bytes"] - previous[key] if key in previous else None
        previous[key] = r["pointer_bytes"]
        extent = " by ".join(str(axis) for axis in r["extent"])
        low, top = r["reserved"]
        out.append(
            f"| {r['board']} | {r['pane']} | {r['headroom']} | {low} to {top} | {extent} "
            f"| {r['pointer_bytes']:,} | {'-' if step is None else f'+{step:,}'} "
            f"| {r['atlas_bytes']:,} |"
        )
    return out


def is_headed(path: pathlib.Path) -> bool:
    return path.parent.name in headed.SESSIONS or path.parent.parent.name == "headroom-check"


def manifest(out: pathlib.Path, logs: list[pathlib.Path]) -> str:
    round_name = out.name
    headless = {provenance(log) for log in logs if not is_headed(log)}
    commits = ", ".join(f"`{commit}`" for commit in sorted(headless))
    lines = [
        "# Raw receipts kept out of tree",
        "",
        "Under ruling 255 of the wing design record, the raw logs of the scene",
        "board's paging receipts live outside the repository, in",
        f"`Code/testing/isometry/receipts/2026-09-26/scene-board-paging/{round_name}/`",
        "on the machine that ran them; paths below are relative to that folder. The",
        "summary (`summary.md`) and the scripts that run the receipts and rebuild the",
        "summary (`receipts.py`, `headed.py`) stay here. Check a copy against its",
        "hash, then `python receipts.py --summarise-only --out <dir>` rebuilds the",
        "summary from it. An earlier round's files stay where they were, hashed by",
        "the manifest committed with that round.",
        *(
            [
                "",
                "`set-aside-noisy-window/` beside these holds a first headed round taken",
                "while other lanes loaded the machine, its demo controls reading up to",
                "16.08 ms. It is kept, and not summarised; the rounds below replaced it.",
            ]
            if (out / "set-aside-noisy-window").is_dir()
            else []
        ),
        "",
        f"Source: commit {commits}, test `paging_receipts_at_256` in",
        "`crates/isometry-views/src/scene/paging_tests.rs`, run with",
        "`--ignored --nocapture --test-threads=1`, and `--release` for the release log.",
        "Each log opens with its commit, command and compiler; each headed session's",
        "`source.txt` names its commit, binary hash and switches.",
        "",
        "| File | Bytes | SHA-256 |",
        "| --- | --- | --- |",
    ]
    for log in logs:
        digest = hashlib.sha256(log.read_bytes()).hexdigest()
        name = log.relative_to(out).as_posix()
        lines.append(f"| `{name}` | {log.stat().st_size:,} | `{digest}` |")
    return NEWLINE.join(lines) + NEWLINE


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", type=pathlib.Path)
    parser.add_argument("--builds", default="debug,release")
    parser.add_argument("--summarise-only", action="store_true")
    parser.add_argument("--host", action="append", default=[], metavar="NAME=EXE")
    parser.add_argument("--check", action="append", default=[], metavar="NAME=EXE=LAYERS")
    args = parser.parse_args()
    if args.out is None:
        args.out = RECEIPTS / output(["git", "rev-parse", "--short", "HEAD"])
    args.out.mkdir(parents=True, exist_ok=True)
    builds = args.builds.split(",")
    if args.summarise_only:
        logs = [args.out / f"{build}.log" for build in builds]
    else:
        logs = [run(build, args.out) for build in builds]
    for index, host in enumerate(args.host, start=1):
        name, exe = host.split("=", 1)
        headed.run(pathlib.Path(exe).resolve(), args.out / f"host-{index}-{name}", name, ROOT)
    for index, check in enumerate(args.check, start=1):
        name, rest = check.split("=", 1)
        exe, layers = rest.rsplit("=", 1)
        directory = args.out / "headroom-check" / f"headroom-{layers}-run-{index}"
        headed.check(pathlib.Path(exe).resolve(), directory, name, ROOT, int(layers))
    rows = [row for log in logs for row in records(log)]
    summary = summarise(rows) + headed.section(args.out) + headed.pictures(args.out)
    (HERE / "summary.md").write_text(summary, encoding="utf-8", newline=NEWLINE)
    raw = logs + headed.files(args.out)
    (HERE / "RAW_RECEIPTS.md").write_text(
        manifest(args.out, raw), encoding="utf-8", newline=NEWLINE
    )
    print(f"{len(rows)} receipts from {', '.join(str(log) for log in logs)}")


if __name__ == "__main__":
    main()
