"""Run the scene board's paging receipts and summarise them (ruling 255).

Runs `paging_receipts_at_256` from `crates/isometry-views` in the debug and
release builds, keeps each raw log out of tree, and writes the summary and the
raw-receipt manifest beside this script:

    python testing/scene-board-paging/receipts.py [--out DIR] [--builds debug,release]
    python testing/scene-board-paging/receipts.py --summarise-only [--out DIR]
    python testing/scene-board-paging/receipts.py --summarise-only --headed-exe EXE

`--headed-exe` also runs the two headed sessions `headed.py` describes, with
the shipping host binary EXE, before summarising; it needs a desktop session.

DIR defaults to ~/Code/testing/isometry/receipts/2026-09-26/scene-board-paging,
the machine's out-of-tree receipt directory. `--summarise-only` rebuilds the
summary from logs already there, so a copy checked against RAW_RECEIPTS.md can
be summarised again without re-running anything. Each log opens with the
commit, command and compiler that produced it.
"""

import argparse
import hashlib
import json
import pathlib
import statistics
import subprocess
import sys
from collections import defaultdict

import headed

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parents[1]
DEFAULT_OUT = (
    pathlib.Path.home() / "Code" / "testing" / "isometry" / "receipts" / "2026-09-26"
    / "scene-board-paging"
)
TAG = "[paging-receipt] "
NEWLINE = chr(10)


def output(command: list[str]) -> str:
    return subprocess.run(
        command, cwd=ROOT, capture_output=True, text=True, check=True
    ).stdout.strip()


def run(build: str, out: pathlib.Path) -> pathlib.Path:
    command = ["cargo", "test", "-p", "isometry-views", "--lib"]
    if build == "release":
        command.append("--release")
    command += ["paging_receipts_at_256", "--", "--ignored", "--nocapture", "--test-threads=1"]
    header = NEWLINE.join([
        f"# commit {output(['git', 'rev-parse', 'HEAD'])}",
        f"# build {build}: {' '.join(command)}",
        f"# {output(['rustc', '-V'])}",
        "",
    ])
    log = out / f"{build}.log"
    result = subprocess.run(command, cwd=ROOT, capture_output=True)
    divider = (NEWLINE + "--- stderr ---" + NEWLINE).encode()
    log.write_bytes(header.encode() + result.stdout + divider + result.stderr)
    if result.returncode != 0:
        sys.exit(f"{' '.join(command)} failed; see {log}")
    return log


def provenance(log: pathlib.Path) -> str:
    """The commit a log's header names."""
    first = log.read_text(encoding="utf-8", errors="replace").splitlines()[0]
    return first.removeprefix("# commit ").strip()


def records(log: pathlib.Path) -> list[dict]:
    # The first receipt shares its line with libtest's `test <name> ...`.
    rows = []
    for line in log.read_text(encoding="utf-8", errors="replace").splitlines():
        at = line.find(TAG)
        if at >= 0:
            rows.append(json.loads(line[at + len(TAG):]))
    return rows


def median(values):
    values = [v for v in values if v is not None]
    return statistics.median(values) if values else None


def ms(value) -> str:
    return "-" if value is None else f"{value:,.2f}"


def summarise(rows: list[dict]) -> str:
    base = {(r["build"], r["board"]): r for r in rows if r["kind"] == "baseline"}
    groups = defaultdict(list)
    for r in rows:
        if r["kind"] != "baseline":
            groups[(r["build"], r["board"], r["pane"], r["kind"])].append(r)
    keys = sorted({k[:3] for k in groups})
    work = lambda r: r["columns_ms"] + r["diff_ms"] + r["fill_ms"]  # noqa: E731
    out = [
        "# Scene board paging receipts, 2026-09-26",
        "",
        "Generated by `receipts.py` from the raw logs named in `RAW_RECEIPTS.md`.",
        "Medians over each run's samples. Every timing is one build on one",
        "machine and moves with both; every count and byte figure does not.",
        "",
        "## One click at 256 by 256",
        "",
        "A click selects a tile, which tints its top voxel. Before paging it",
        "raised the whole ground and compared it brick by brick; now it reads",
        "one column per tile, diffs them and remakes the held bricks it touched.",
        "",
        "| build | board | pane | before: regrow + diff, ms | now: columns + diff + fill, ms"
        " | frame, ms | slots | upload, bytes |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for build, board, pane in keys:
        clicks = groups.get((build, board, pane, "select"), [])
        if not clicks:
            continue
        old = base.get((build, board))
        before = old["grow_ms"] + old["diff_ms"] if old else None
        out.append(
            f"| {build} | {board} | {pane} | {ms(before)} | {ms(median(map(work, clicks)))} "
            f"| {ms(median(r['draw_ms'] for r in clicks))} "
            f"| {median(r['slots'] for r in clicks)} "
            f"| {median(r['upload_bytes'] for r in clicks):,.0f} |"
        )
    out += [
        "",
        "## One raise, one pan",
        "",
        "A raise lifts one tile a step. A pan moves the camera a tile across or",
        "half a tile down: it reads nothing, and it retargets, or, while the hold",
        "stands, rebuilds whenever the framing shrinks.",
        "",
        "| build | board | pane | kind | n | columns + diff + fill, ms | frame, ms"
        " | loaded | retargets | hold rebuilds | upload, bytes |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for build, board, pane in keys:
        for kind in ("raise", "pan"):
            sample = groups.get((build, board, pane, kind), [])
            if not sample:
                continue
            retargets = sum(
                1 for r in sample if r["rebuilt"] is None and r["loaded"] + r["evicted"] > 0
            )
            holds = sum(1 for r in sample if r["rebuilt"] == "shrink")
            out.append(
                f"| {build} | {board} | {pane} | {kind} | {len(sample)} "
                f"| {ms(median(map(work, sample)))} "
                f"| {ms(median(r['draw_ms'] for r in sample))} "
                f"| {median(r['loaded'] for r in sample)} | {retargets} | {holds} "
                f"| {median(r['upload_bytes'] for r in sample):,.0f} |"
            )
    out += [
        "",
        "## What the frame holds",
        "",
        "| build | board | pane | bricks on the board | resident | capacity | past the atlas"
        " | first frame, ms | first fill, ms |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for build, board, pane in keys:
        first = groups.get((build, board, pane, "first"), [])
        held = [r for k, v in groups.items() if k[:3] == (build, board, pane) for r in v]
        if not first:
            continue
        old = base.get((build, board))
        out.append(
            f"| {build} | {board} | {pane} | {old['bricks'] if old else '-'} "
            f"| {min(r['resident'] for r in held)} to {max(r['resident'] for r in held)} "
            f"| {first[0]['capacity']} | {max(r['overflow'] for r in held)} "
            f"| {ms(first[0]['draw_ms'])} | {ms(first[0]['fill_ms'])} |"
        )
    return NEWLINE.join(out) + NEWLINE


def is_headed(path: pathlib.Path) -> bool:
    return path.parent.name in headed.SESSIONS


def manifest(logs: list[pathlib.Path]) -> str:
    headless = {provenance(log) for log in logs if not is_headed(log)}
    commits = ", ".join(f"`{commit}`" for commit in sorted(headless))
    lines = [
        "# Raw receipts kept out of tree",
        "",
        "Under ruling 255 of the wing design record, the raw logs of the scene",
        "board's paging receipts live outside the repository, in",
        "`Code/testing/isometry/receipts/2026-09-26/scene-board-paging/` on the",
        "machine that ran them. The summary (`summary.md`) and the script that runs",
        "the receipts and rebuilds the summary (`receipts.py`) stay here. Check a",
        "copy against its hash, then `python receipts.py --summarise-only --out",
        "<dir>` rebuilds the summary from it.",
        "",
        f"Source: commit {commits}, test `paging_receipts_at_256` in",
        "`crates/isometry-views/src/scene/paging_tests.rs`, run with",
        "`--ignored --nocapture --test-threads=1`, and `--release` for the release log.",
        "Each log opens with its commit, command and compiler; each headed session's",
        "`source.txt` names its commit, binary hash and switches.",
        "",
        "| File | Bytes | SHA-256 |",
        "| --- | --- | --- |",
    ]
    for log in logs:
        digest = hashlib.sha256(log.read_bytes()).hexdigest()
        name = f"{log.parent.name}/{log.name}" if is_headed(log) else log.name
        lines.append(f"| `{name}` | {log.stat().st_size:,} | `{digest}` |")
    return NEWLINE.join(lines) + NEWLINE


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", type=pathlib.Path, default=DEFAULT_OUT)
    parser.add_argument("--builds", default="debug,release")
    parser.add_argument("--summarise-only", action="store_true")
    parser.add_argument("--headed-exe", type=pathlib.Path)
    args = parser.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)
    builds = args.builds.split(",")
    if args.summarise_only:
        logs = [args.out / f"{build}.log" for build in builds]
    else:
        logs = [run(build, args.out) for build in builds]
    if args.headed_exe:
        headed.run(args.headed_exe.resolve(), args.out, output(["git", "rev-parse", "HEAD"]), ROOT)
    rows = [row for log in logs for row in records(log)]
    summary = summarise(rows) + headed.section(args.out)
    (HERE / "summary.md").write_text(summary, encoding="utf-8", newline=NEWLINE)
    raw = logs + headed.files(args.out)
    (HERE / "RAW_RECEIPTS.md").write_text(manifest(raw), encoding="utf-8", newline=NEWLINE)
    print(f"{len(rows)} receipts from {', '.join(str(log) for log in logs)}")


if __name__ == "__main__":
    main()
